<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OmenSpace.Hardware\OmenSpace.Hardware.csproj" />
    <ProjectReference Include="..\OmenSpace.Core\OmenSpace.Core.csproj" />
    <ProjectReference Include="..\OmenSpace.Worker\OmenSpace.Worker.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
