<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OmenSpace.Core\OmenSpace.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="drivers\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="8.0.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.9" />
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>


  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CodePage>65001</CodePage>
  </PropertyGroup>

</Project>
